### ISSUE TITLE
Site returns status code 503

### ISSUE THREAD

**Issue by janosh** [snuffyDev/Beatbump#1]
Hey there, https://beatbump.ml appears to be returning a status code of 503 every now then. Came up in my CI: https://github.com/janosh/awesome-svelte-kit/runs/3202616716?check_suite_focus=true

Feel free to close if won't fix.

**Comment by snuffyDev** [comment]
Hello! Thanks for catching that! I think it _*should*_ be fixed now. I must've done something on the last build. The issue most likely was the load function. If there are any issues again, feel free to open another issue. I'm going to implement some safeguards to prevent this as best as I can.
