### ISSUE TITLE
Feature Request: A time-stamp next to, or above, the length line

### ISSUE THREAD

**Issue by SecularSteve** [snuffyDev/Beatbump#100]
It's only a suggestion, I'm not trying to look unreasonable.

On the right side could be the full length of the song in minutes : seconds (or hours maybe).
On the left side could be at which time point that line the song is currently playing.

Something like this
![Screenshot 2022-09-01 at 17-26-07 Dynoro ft  Gigi D'Agostino - In My Mind скачать бесплатно в mp3 слушать онлайн текст песни видео (клип)](https://user-images.githubusercontent.com/33793273/187952566-96f7183c-bf9d-4312-99bd-7bee2f88e088.png)
(only that they're located on opposite ends of the line)

**Comment by IronMaltese** [comment]
This request isn't unreasonable, Youtube Music and Spotify have this feature here's how they look:

![image](https://user-images.githubusercontent.com/89056889/188013861-9ad1f08c-447f-4a70-a771-b85e2f9e6eed.png)

![image](https://user-images.githubusercontent.com/89056889/188013873-8acd634d-2356-4402-907a-b44c466818f2.png)

**Comment by snuffyDev** [comment]
Wow, Beatbumps about to turn two years old in a few months. How could I have overlooked this??

Working on it now! Thanks!

**Comment by SecularSteve** [comment]
> The project's popularity has skyrocketed these past few months, congrats on finding such a big audience, well deserved🤙🤙🤙

I'd like to think it's because people started realising that Invidious and Piped still have very shoddy support for auto-generated Topic channels.
Not only do they need very specifically fine tuned instances to view anything on their pages, but they don't evne come with a "Topic Only" option in the Filter Bar.

Speaking of which, I just realised Beatbump doesn't have a "Repeat" button.
Any chance this could be placed in the to-do list while you're at it? I'll make the icon if you want.

**Comment by IronMaltese** [comment]
@SecularSteve Wanna close this and open a new issue for implementing the repeat button to keep things organized

**Comment by SecularSteve** [comment]
Sure, no worries.
