### ISSUE TITLE
Put About this artist on bottom of mobile artist pages

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#101]
On Beatbump's mobile view, About this artist disappears, it should be put on the bottom of the artist's page like how it is on the YouTube Music app referenced here:

![image](https://user-images.githubusercontent.com/89056889/188024048-4ad8bea5-025d-4117-a9be-33a60071c666.png)

**Comment by snuffyDev** [comment]
Almost added! Some issues still, but they’ll be fixed soon!
![F555FAA3-6438-42CB-8701-E86095A5DAEF](https://user-images.githubusercontent.com/72365477/191004155-f493e85b-5278-4f3a-bcaa-75b589cb99a1.png)

**Comment by snuffyDev** [comment]
I’m gonna mark this as closed now, since it’s implemented, but will be tweaked more in the future !

https://user-images.githubusercontent.com/72365477/191028241-00f3303e-5ccf-447c-9c0e-542ac163042c.MOV
