### ISSUE TITLE
Volume bar cut out

### ISSUE THREAD

**Issue by martadinata666** [snuffyDev/Beatbump#106]
The volume bar only show bottom bit instead all bar, i think it breaks on this https://github.com/snuffyDev/Beatbump/commit/6dd0caa97dd0a996264d21d9206bb695c8ad7d9a
![2022-09-16-084947_237x176_scrot](https://user-images.githubusercontent.com/2433562/190539291-8a94724c-2814-4dc7-a953-ac51834da76f.png)

**Comment by snuffyDev** [comment]
I believe it should be fixed now? Let me know! I also improved the volume bar so it’s less finicky. It’s also exponential now, so it’ll feel more natural to use! Let me know how things are!

**Comment by martadinata666** [comment]
At main site, `beatbump.ml` got no issues, i forgot to tell that i build my self from github repo `master` branch, is there some code that not pushed yet?

**Comment by snuffyDev** [comment]
Just committed now, as well as published a new Docker image. 

It should work now that the changes are published to the repo, so just make sure you have the latest commit :)

`docker pull snuffydev/beatbump:master` is the updated pre-built image, in case you wanted to test it prior to building.

**Comment by martadinata666** [comment]
Thanks, last commit got the fix
