### ISSUE TITLE
Unable to open certain albums and artists

### ISSUE THREAD

**Issue by onny** [snuffyDev/Beatbump#11]
Hey,
there's one album of Paul McCartney called RAM. I'm able to find the songs here https://beatbump.ml/search/mccartney%2520ram?filter=EgWKAQIIAWoKEAMQBBAKEAkQBQ%3D%3D

But something is wrong in displaying it. The album should be caleld "RAM" by the artist "Paul and Linda McCartney" but it is not correctly displayed.

Further trying to go to the artist or album page fails.

Best regards
Jonas

**Comment by snuffyDev** [comment]
![5F61AC7A-B77B-4754-AF5E-BAC98EE6FD63](https://user-images.githubusercontent.com/72365477/150066014-9a28bfab-18b3-4e3c-ac61-6f4fe4e76bac.png)
![0798EB48-CCD6-4395-8656-CC1293F6F4A7](https://user-images.githubusercontent.com/72365477/150066015-61df7191-6947-48dc-b04a-a7cbc9fb5e02.png)

it should be fixed now

**Comment by onny** [comment]
Looks good, thank you!
