### ISSUE TITLE
autoplay takes awhile on ios

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#115]
After start listening is pressed on a link like: 
https://beatbump.ml/listen?id=qsUXeXms8FQ on iOS, 

The song should play quickly, instead of taking a solid amount of time to begin compared to how fast Beatbump would actually take to load the song

**Comment by IronMaltese** [comment]
User error on my end, but it takes a long enough time for the song to load here that a new user would think something is wrong

**Comment by snuffyDev** [comment]
Is this with the HTTP or HLS streaming?

**Comment by IronMaltese** [comment]
> Is this with the HTTP or HLS streaming?

I just realized it's only with HTTP, I can close this with HlS soon going to be the default
