### ISSUE TITLE
Can’t add songs to custom playlists

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#12]
When “add to playlist” is hit, the song doesn’t show up in the custom playlist, I’m on iOS

**Comment by snuffyDev** [comment]
Hello! Thanks for submitting this issue. Can you give more detail on the situation? Like is the issue occurring everywhere? Or just on the search page, or the trending page etc.? I'll start looking into this now while I wait for a response

**Comment by snuffyDev** [comment]
After looking into it, it appears I have fixed it. At least in development it's fixed, waiting for Cloudflare Pages to finish building the update I pushed in order to test it on my iPhone. Will let you know the results!

**Comment by snuffyDev** [comment]
It works now, at least on my end. Let me know if it's fixed or if there's any other issues with it!

**Comment by IronMaltese** [comment]
It works now, thanks you
