### ISSUE TITLE
Albums and Playlists not working

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#120]
<img width="790" alt="Screen Shot 2022-11-01 at 8 15 43 PM" src="https://user-images.githubusercontent.com/89056889/199365527-94412563-0e71-4de3-a113-536794c83c3c.png">

**Comment by snuffyDev** [comment]
Should be fixed and working better than ever! Let me know if you noticed any improvements

**Comment by IronMaltese** [comment]
It works just as normal again, thanks!
