### ISSUE TITLE
Songs take too long to start playing

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#13]
Songs take a few seconds before clicking on them, and a few seconds for auto play

**Comment by snuffyDev** [comment]
This is probably due to how many steps I implemented for song playback, along with the suboptimal methods I seem to have added such as `array.find(...)` plus reading from local storage every playback request. I'll experiment with ways to cut down the time it takes, as in the past it certainly was faster. I'll let you know of any updates!

**Comment by snuffyDev** [comment]
Update: I've currently shaved ~2-3 seconds off, tested both with my mobile network (4G LTE but weak enough signal that it's same speed as 3G) and devtools 'slow 3g' throttling. Experimenting to see what else can be done

**Comment by IronMaltese** [comment]
Great work on the latest commits! I've noticed a huge improvement in speed of song playback, so unless you want to keep this issue open, I think it can be closed

**Comment by IronMaltese** [comment]
Comparing iOS and my computer, iOS is noticeably lagging behind, I don't know exactly what this is, but I thought it should be addressed

**Comment by snuffyDev** [comment]
I've noticed it as well, but I'm pretty sure it's mostly on YouTube's end. But hopefully soon I aim to resolve the majority of (potential, or if they exist, they're typically minor) performance issues. I'm slowly trying to do a complete overhaul of the backend and front end to not only clean up the codebase, but to improve performance as well. 

For an example of what I'm talking about, this is the current script for the Playback Queue ([$lib/stores/list](https://github.com/snuffyDev/Beatbump/blob/master/src/lib/stores/list.ts). It's bad, and certainly isn't something I'd write today, let alone something I wanna keep in the repo. 

And here's the rewrite I just started for it:
```typescript
import type { Item } from '$lib/types';
import { getSrc } from '$lib/utils';

import {type Writable, writable} from 'svelte/store'

interface ISessionListProvider {
	currentMixId: string;
	continuation: string;
	clickTrackingParams: string;
	mix: Array<Item>
}

interface ISessionListService {
  subscribe: Writable<ISessionListProvider>['subscribe']
  /** Initialize a new automix session */
  initAutoMixSession(args: {
		videoId?: string;
		playlistId?: string;
		keyId?: number;
		playlistSetVideoId?: string;
		clickTracking?: string;
		config?: { playerParams?: string; type?: string };
	}): Promise<void>;
	/** Initializes a new playlist session */
	initPlaylistSession(args: {playlistId: string, index?: number}): Promise<{body:string; error?: boolean;}>
	
	/** Continues current automix session by fetching the next batch of songs */
	getSessionContinuation(args: {itct: string, videoId: string, playlistId: string, ctoken: string, clickTrackingParams: string, key: number})
	
	/**
	 * Fetches a set of similar songs and appends them to the current
	 * automix session 
	 */
	getMoreLikeThis(args: {videoId: string; autoMixList?: string}): Promise<void>;
	
	
	setTrackWillPlayNext(item: Item, key: number): Promise<void>;

	removeTrack(index: number): void;

	shuffle(preserveBeforeActive?: boolean): void;



}


	
const SessionListService: ISessionListService  = _sessionListService();
function _sessionListService(): ISessionListService {
	const {set,subscribe,update} = writable<ISessionListProvider>({})
	return {
		subscribe,
		async initAutoMixSession({clickTracking,keyId,playlistId,playlistSetVideoId,videoId,config:{playerParams = '', type = ''} = {}}){

		},
		async initPlaylistSession(args) {
			const {playlistId = '',index = 0} = args;
			return await getSrc('',playlistId)
		},
		
	}
}
```
Still very early, but after I rewrite a decent bit of the code, it should be faster -- but if it isn't, the code would at least be 100x more readable.

**Comment by IronMaltese** [comment]
This new code looks really good, and any improvement to the backend will probably speed it up and make contributions from other developers easier

**Comment by IronMaltese** [comment]
Do you think you can use the rewrite to fix the problem of songs on iOS showing that they're double the length they actually are?

**Comment by snuffyDev** [comment]
> Do you think you can use the rewrite to fix the problem of songs on iOS showing that they're double the length they actually are?

Unfortunately that is a problem with YouTube’s encoding of the files. Every other device works because they properly can estimate the time using the range headers or content length, having a brain fart and can’t remember which one it is.

As for the rewrite overall, I have figured out the best way to iterate over YTMs massive JSON results (at least in most circumstances). The average time to load a specific playlist page on the dev server originally was 700-850ms. But now it’s looking like it should consistently return a response in anywhere from 550-700. The 700ms is just a guesstimate though. Cause I’ve seen it go up to that, or up to 750, but from my current testing it seems to be a here and there sorta thing. 

Just need to make the response time more consistent now

**Comment by snuffyDev** [comment]
I've pushed a build that's been live since last night I think, if not then it was this morning. Just in case I pushed it again. Let me know if you have or do notice speed improvements, specifically with the home page, and loading normal playlist pages (example below)


https://user-images.githubusercontent.com/72365477/158711911-cc102c6c-511c-40a5-bdfa-8d298ab52f34.MOV

**Comment by IronMaltese** [comment]
I definitely notice the improvements on desktop, since song playback is basically instant but on iOS, songs still seem to take weirdly long to play, but the homepage and trending on both desktop and iOS are flawlessly fast, great job! But the library page on iOS seems to take a long time to load my library, is there a way to store my library in the browser so it doesn't have to load everytime, since the library page (especially when you have multiple playlists) takes awhile, so I usually wait to let the page load before handing my phone to someone and letting them play a song

**Comment by IronMaltese** [comment]
Also I noticed you centered the play album and play radio buttons for playlists, it's got me wondering if you're planning on implementing Tidal's design for albums and playlists 😆![image](https://user-images.githubusercontent.com/89056889/158714361-241f1023-ac70-4150-8747-4cdf5a495282.jpeg)

**Comment by IronMaltese** [comment]
If you do implement this design, it would be best to just have two lines for the title of the album and another for everything else

**Comment by IronMaltese** [comment]
Also you can get rid of the gray box Beatbump currently has on albums and playlists, and maybe even add the fancy background that tidal has for albums and playlists, but if this is added, try to make it much more compact than tidal since the songs in the album and playlists should actually be visible, unlike tidal where they own show two songs when the user is at the top of the page

**Comment by IronMaltese** [comment]
![image](https://user-images.githubusercontent.com/89056889/158894733-05a6727c-55ae-4af4-8187-530aa2352702.png) for albums and playlists, the information section and description for playlists is on the left and looks incongruous, also the redesign looks great!

**Comment by snuffyDev** [comment]
Nice catch, didn’t catch that earlier. Will fix soon

**Comment by snuffyDev** [comment]
Some hopeful progress has been made with this, albeit iOS doesn’t support Media Source Extensions, but progress nonetheless. All I’d have to do for iOS is serve the HLS streams directly instead of using hls.js

https://github.com/snuffyDev/Beatbump/issues/82#issuecomment-1195813976

**Comment by IronMaltese** [comment]
> Some hopeful progress has been made with this, albeit iOS doesn’t support Media Source Extensions, but progress nonetheless. All I’d have to do for iOS is serve the HLS streams directly instead of using hls.js
> 
> 
> 
> https://github.com/snuffyDev/Beatbump/issues/82#issuecomment-

I'm gonna close this issue since speed could probably be worked on, the average user won't have a problem with the current speed, you can reopen if you disagree
