### ISSUE TITLE
[BUG] Can't remove music from playlist 

### ISSUE THREAD

**Issue by Hyper-1337** [snuffyDev/Beatbump#131]
When I try to remove a song from my playlist it does nothing and I am self-hosting it on docker.

**Comment by snuffyDev** [comment]
It should be fixed now, I think. Docker image should be updated

**Comment by Hyper-1337** [comment]
Ok I will check

**Comment by Hyper-1337** [comment]
It works I can now remove a song from my playlist

**Comment by snuffyDev** [comment]
Glad it works!
