### ISSUE TITLE
The duration is longer than the song(s)’s avarage one.

### ISSUE THREAD

**Issue by wanniethecharacter** [snuffyDev/Beatbump#138]
Like my heart will go on by celine dion is 4:40 but the duration on this website is 9:20. And when the song’s finished you can hear silence for like 3-5 minutes.

**Comment by snuffyDev** [comment]
Testing a fix at this current moment!

**Comment by snuffyDev** [comment]
Fix should be live on the main instance, please let me know if it’s fixed for you, whenever you get the chance. Thank you!
