### ISSUE TITLE
[BUG] Shuffle don't work on phone (android /iOS)

### ISSUE THREAD

**Issue by Klos54** [snuffyDev/Beatbump#142]
The shuffle button doesn't work i.e the songs are not played into the shuffle mode, the songs are played into order.

1. Go to a playlist
2. Click on shuffle button
4. See the playlist is played into order and not into the shuffle mode

 - OS: android & iOS
 - Browser : firefox, chrome

**Comment by snuffyDev** [comment]
Fixed, thank you! Closing this issue now, re-open if it still continues
