### ISSUE TITLE
[BUG] Animations uses only one thread, which makes the interface laggy.

### ISSUE THREAD

**Issue by GamePlayer-8** [snuffyDev/Beatbump#162]
**Describe the bug**
As the title says, FPS drops down to around 1 - 10, when using i.e. Playlist UI.

**To Reproduce**
1. Play some music.
2. Open playlist (FPS drop should be already noticed)
3. Try hovering the cursor on next songs from the playlist.

**Expected behavior**
FPS amount should stay the same as before (^60 FPS).

**Desktop (please complete the following information):**
 - OS: `Artix Linux Rolling OpenRC / Xfce - X11`.
 - Browser `LibreWolf` ||(FireFox fork)||.
 - Version ||(read from UA)|| `Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0`.

**Comment by snuffyDev** [comment]
The problem is Firefox's rendering engine can't handle opening animation because of the blur filter used for Immersive view. Does disabling the Immersive view in the settings fix the lag for you?

**Comment by GamePlayer-8** [comment]
How to disable it?

**Comment by snuffyDev** [comment]
https://user-images.githubusercontent.com/72365477/233204541-35f85b44-29f4-419f-a851-3efc5f8d2c8c.MOV

Here's how to disable it, I'm on my phone right now but everything will be in the same place UI-wise 🫡

**Comment by GamePlayer-8** [comment]
Helped a lot although a bit of frame drop can be noticed.

Can Beatbump turn off the Immersive Queue when UA != Chrome?

**Comment by snuffyDev** [comment]
https://github.com/snuffyDev/Beatbump/assets/72365477/d781fd30-4ab1-4c6e-9009-9f47cc71348c

Took a little bit, my apologies, but good news -- I've fixed it as part of the rewrite

**Comment by GamePlayer-8** [comment]
No need to apologies. Ur doing a great work, uwu. <img alt="blobcat_heart" src="https://media.tech.lgbt/custom_emojis/images/000/070/510/original/9a94cae6ccf7cff6.png" width="15" />

Closing issue.
