### ISSUE TITLE
[FEAT] "Why Beatbump?"

### ISSUE THREAD

**Issue by qdhj** [snuffyDev/Beatbump#170]
"Why Beatbump?" **definitely** needs a mention of high security & privacy, when using Beatbump instead of Google Youtube music.

**Comment by maboroshin** [comment]
No mention of ```security``` at currently readme. What is there is ```privacy```.

> A privacy-respecting alternative frontend for YouTube Music. 
> Beatbump is a fully-featured music listening experience, while helping to ease your privacy concerns associated with other platforms.

Inspired by Invidious, it probably avoids associating a listen history. You probably want to hear the details of what this is doing.
