### ISSUE TITLE
When playing a playlist, songs will skip mid way

### ISSUE THREAD

**Issue by giwty** [snuffyDev/Beatbump#198]
**Describe the bug**
Songs do not fully complete before going to the next song, the next song will start mid way of the previous one.
This is when using HLS on iOS, tested on both Safari/firefox/Chrome.
When using streaming through HTTP and not HLS, im getting a different problem of songs are running for double the time, meaning that there will be long pause of silence between songs.

**To Reproduce**
1. On an iOS device, choose HLS as streaming
2. Choose any playlist and start listening
3. Notice how songs do not completely finish and move on to the next

**Expected behavior**
Songs complete playing before moving to the next

**Screenshots**

**Smartphone (please complete the following information):**
 - OS: iOS
 - Browser same on all 3 browsers
 - Version 16

**Additional context**
Love this application, really appriciate the efforts, and looking to try the new big update.

**Comment by snuffyDev** [comment]
https://preview.beatbump.io/home

Does the new update (preview build) work for you?

**Comment by giwty** [comment]
Let me test and report back, will close and re-open if i see the sane behavior.
Thanks
