### ISSUE TITLE
Add to Queue Button doesn't work

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#21]
When Add to Queue is pressed, the song keeps playing, but the buttons in the bottom bar stop working and the song isn't played next

**Comment by snuffyDev** [comment]
Let me know if my recent push fixes it, once it finishes building.  As well as #17, #16, #15

**Comment by IronMaltese** [comment]
I’m on IOS 15.2.1 and the Add to Queue button still doesn’t play the song next, and also breaks the buttons on the bottom bar
