### ISSUE TITLE
[FEAT] Leave search string in search field

### ISSUE THREAD

**Issue by maboroshin** [snuffyDev/Beatbump#220]
**Is your feature request related to a problem? Please describe.**

There are many other services where search terms are left in the input field. We are familiar with this. However I have to enter them from scratch when modifying or adding on Beatbump.

**Describe the solution you'd like**

Leave search string in search field

**Describe alternatives you've considered**

N/A

**Additional context**

Related issue: https://github.com/snuffyDev/Beatbump/issues/109

**Comment by BrightDV** [comment]
Did you try to use this setting? (at the bottom)
![Screenshot_20231231-171854_Brave](https://github.com/snuffyDev/Beatbump/assets/92821484/d4292ead-c9e0-4130-93fb-bc25e678f05c)

**Comment by maboroshin** [comment]
I can't even do it with that setting - Chrome on Windows, Safari on iPhone.

**Comment by maboroshin** [comment]
I currently used an iPhone. I used that setting. The search string remained in Safari on the iPhone.
