### ISSUE TITLE
Artists should appear in circle icons

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#27]
When you look up an artist, their picture appears in a square, making it hard to differentiate a song and an artist

**Comment by snuffyDev** [comment]
Added, just haven’t pushed the code to GitHub yet

**Comment by IronMaltese** [comment]
Thanks man, you’re actually great

**Comment by snuffyDev** [comment]
Appreciate the compliment! Recently started some important things which is why it took awhile. Working on the other issues while I find the time!!
