### ISSUE TITLE
Custom playlist cleared of songs

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#31]
https://user-images.githubusercontent.com/89056889/152706375-74c6b704-7ca2-4b39-a975-226523ed71d1.MOV

This only happened to one playlist, but it’s the playlist with the most songs in it

**Comment by IronMaltese** [comment]
This issue also happened to my favorite songs

**Comment by IronMaltese** [comment]
https://user-images.githubusercontent.com/89056889/155244832-104776fd-1dad-4d94-8f1b-058d0d8dadf0.MOV

**Comment by snuffyDev** [comment]
Don't worry, just wanted to reassure you that I haven't ignored any of the issues!! I've been taking a short break from working on Beatbump since I was sorta burnt out and working on other projects, but I'm starting to work on Beatbump again! Was looking into this during the break and I got some potential causes for it. I'll update you on any changes I make so you can keep an eye out if the problem persists or not

**Comment by IronMaltese** [comment]
It’s great to see you back on the project! While you’ve been gone I’ve been integrating Beatbump into other projects and even got it on Libredirect! I’ve also listed this project on alternativeto, so much more people should be able to know about it. Also I noticed you weren’t verified on brave, idk if you’d be able to do it, but I think it would bring a bit of revenue in for the project. I’m pretty bad at coding, but I learned html awhile back, and I’ve been struggling through learning svelte, I know you’re not accepting pull requests right now, but I would love to start coding in features. It’s great to see you back though, since this is legitimately the best GitHub project I’ve seen

**Comment by IronMaltese** [comment]
Also, quick question, which IDE do you recommend for learning/using svelte, I've been using VScode with the Svelte extension + Svelte intellisense, since that's what I saw some guy on reddit recommend

**Comment by IronMaltese** [comment]
Also here's some more context for this bug, when I click on the playlist cleared of songs, every button on screen stops working, including the play button and skip song, but clicking home or trending changes the url, but it doesn't actually bring me to the home or trending page, so I have to reload and that brings me to home or trending

**Comment by IronMaltese** [comment]
^This is also the same for Your Songs

**Comment by snuffyDev** [comment]
I'll add an especially long error notification, let me come up with a method to reproduce this, since it's possible my IndexedDB code is acting up. It's only on specific playlists and / or the favorited songs, correct?

**Comment by snuffyDev** [comment]
I possibly have fixed this, at least for playlists. It appears when adding a playlist to another playlist, I forgot to put in a type check to verify if it was a single item or an array being added to the playlist. Which ended up causing an error when trying to read the playlist.

Fortunately, I think this means your playlists aren't lost. I'm finishing up testing the code I wrote to repair the playlist, so I should be pushing it to prod soon

**Comment by snuffyDev** [comment]
The changes should be live now, let me know if it’s fixed. Hopefully that was the problem

**Comment by IronMaltese** [comment]
Ayy yo thank you so much, the fix worked for my custom playlist, but "My Songs" still has the same problem, this is less of an issue if you're planning to turn that feature into a "favorites" custom playlist though

**Comment by IronMaltese** [comment]
Actually the playlist still has the problem where pressing anything in the top bar doesn't work, since it only changes the url and I have to reload to get there, and the queue button doesn't do anything either, but the other buttons are fine

**Comment by IronMaltese** [comment]
This behavior is weird, but it seems that when I play a song by pressing it in the playlist, this happens, but when I press "start playlist" the only button that doesn't work is the queue button

**Comment by IronMaltese** [comment]
These problems are very inconsistent, but they happen more than they don’t

**Comment by IronMaltese** [comment]
I can't seem to replicate the issues I had before, but I tested each reported bug above at least 10 times each, and now I can't seem get it once, now the problem is that every button breaks when I press the queue button, I'm not sure why these problems are so inconsistent, but a general theme is the queue button always working before a song is played, but breaking after it's played and every button breaking after some action is performed (playing a song, start playlist, or queue button while a song is playing) Sorry for any confusion, I'm just trying to report these bugs as accurately as possible, thank you for the amazing work

**Comment by snuffyDev** [comment]
Don’t worry, I appreciate you letting me know about any problems! I just changed some code, so let me know if it’s improved.

As for things breaking after playing a song, is that only on custom playlists or does it happen for any playlist (custom and normal ones)?

**Comment by IronMaltese** [comment]
This seems to only apply to the custom playlist that broke before, but albums and my other custom playlists are fine

**Comment by IronMaltese** [comment]
Idk if this means that custom playlists will be able to break the same way in the future

**Comment by snuffyDev** [comment]
Hmm, it seems like its a problem caused by an older update that used broken IndexedDB code. I'll add in the ability to export your data as JSON, if you'd be okay if I asked to give it a look? Seeing as what I posted about a few days ago was caused by IndexedDB code that incorrectly updated playlists:

> I possibly have fixed this, at least for playlists. It appears when adding a playlist to another playlist, I forgot to put in a type check to verify if it was a single item or an array being added to the playlist. Which ended up causing an error when trying to read the playlist.
> 
> Fortunately, I think this means your playlists aren't lost. I'm finishing up testing the code I wrote to repair the playlist, so I should be pushing it to prod soon

My hunch is that it's something along these lines, but unfortunately I regularly clear my web storage, so I wouldn't be able to recreate any potential bugs. Is this something you'd be okay with?

**Comment by IronMaltese** [comment]
I'd definitely be down to test if this still happens after exporting my data to JSON and moving it to a new browser/device

**Comment by IronMaltese** [comment]
The only reason this has stayed open is because of exporting data through JSON, if a problem arises from that a new issue should be opened
