### ISSUE TITLE
Website seems to be broken

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#36]
After the latest commits, the website on iOS seems to have multiple features that are completely broken (playing songs, searching, and opening albums)

**Comment by IronMaltese** [comment]
https://user-images.githubusercontent.com/89056889/157157147-1530958d-54ba-46b7-9485-9a88b980f39e.MOV

**Comment by snuffyDev** [comment]
https://user-images.githubusercontent.com/72365477/157162376-1a307472-df0b-42ac-ad7a-63c7a2a6785a.MOV

That’s odd, it works for me. Loaded it in a Private tab, so none of its cached. I’ll see what’s going on

**Comment by IronMaltese** [comment]
It’s working now, no worries
