### ISSUE TITLE
Unable to play shared song

### ISSUE THREAD

**Issue by onny** [snuffyDev/Beatbump#5]
Hey,
thanks this project is great and it looks fantastic!

Currently I'm unable to play a shared link, for example https://beatbump.ml/listen?id=qsUXeXms8FQ
I'm getting "No audio stream found, skipping"

Regards
Jonas

**Comment by snuffyDev** [comment]
Hello! My apologies for seeing this so late! I'm working on fixing this immediately. Will let you know ASAP when I fix this. Great song choice by the way ;)

**Comment by snuffyDev** [comment]
Hello! I'm happy to confirm that as far as I've tested, it should now be fixed :) I'll leave this issue open just in case there's any issues, but if the bug has been resolved, feel free to close this.

To verify, check this link and see if it works: https://beatbump.ml/listen?id=skoacDK2zcw

**Comment by onny** [comment]
Works great now! That the UI is switching back to the trending page is a bit confusing. Maybe one could stick at the "Start listening" shared song view and just change the button to "Pause"?

**Comment by snuffyDev** [comment]
Good idea, initially when I implemented the listen page it was just to get it in there and functional, never actually got around to de-jenkifying it yet! Will begin working on that very soon!
