### ISSUE TITLE
Site seems to be broken 

### ISSUE THREAD

**Issue by Remisence** [snuffyDev/Beatbump#50]
Both on my phone on which I use Bromite and on my PC on which I use Librewolf. Nothing works 
![Screenshot 2022-03-28 at 17-03-58 Home](https://user-images.githubusercontent.com/81119716/160450316-7d26bf64-38c9-4d10-ae33-0d4cf0115f0c.png)

**Comment by IronMaltese** [comment]
I've tested this on librewolf for macos and am experiencing the same issue, even when ublock origin shields are down, no links work and images don't show up, I'm not sure what Librewolf blocks that would cause this

**Comment by IronMaltese** [comment]
I'm looking through about:config right now to try and find the problem

**Comment by IronMaltese** [comment]
The issue seems to be that beatbump doesn't work on firefox-based browsers, since it doesn't work with a vanilla install of firefox, the site is going through a re-write right now, so that would be great if this issue can be focused on for the rewrite

**Comment by IronMaltese** [comment]
The only short-term solution would be to use beatbump in a separate browser while this is worked on

**Comment by Remisence** [comment]
Well I don't think the site is working at all, given that it isn't working on Bromite which is a Chromium based browser

**Comment by IronMaltese** [comment]
The site works for me on Brave for MacOs and Safari for iOS

**Comment by IronMaltese** [comment]
I'm not sure about Bromite since I have no way to test android browsers

**Comment by IronMaltese** [comment]
Can you try another chromium based android browser, because Bromite might be blocking something essential for beatbump to work

**Comment by Remisence** [comment]
Doesn't work with Brave either

**Comment by IronMaltese** [comment]
Interesting, I don't think that @snuffyDev has an android device to test this on, but I'll wait for his response

**Comment by IronMaltese** [comment]
Nevermind, I loaded up Beatbump in a private tab and have this issue, this applies to all browsers

**Comment by snuffyDev** [comment]
Give me a little I'll sort this out. It seems the problem is the service worker or the CSP. Don't know how, when, or why it broke (considering i pushed the latest build 2 days ago, and it worked when i used beatbump yesterday) but I'll tweak both and push an update real quick. Weird to see something like this happen again. My apologies for the late reply. Will reply when I push it and I'll verify if it's working.

**Comment by snuffyDev** [comment]
Try it now, I disabled the CSP. Should also allow for more flexibility with using alternative urls for images. Works on a cache-cleared Incognito Edge tab, as well as my iPhone. My Galaxy is dead or else I'd test on that, but it should work now

**Comment by IronMaltese** [comment]
It works for me! This project never fails to impress with the quick fixes and fast development, thanks!

**Comment by Remisence** [comment]
It works now.
