### ISSUE TITLE
Boxes around everything

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#53]
Beatbump uses visible boxes for grouping elements and making sure they behave properly but the problem for me is that they make the website look bad, I'm not sure if there's a way these boxes can blend into the background or if they're not needed at all but I think it would be better without them ex: ![image](https://user-images.githubusercontent.com/89056889/160967250-136eda67-2355-4183-a23a-a7af126d61cd.png)!!![image](https://user-images.githubusercontent.com/89056889/160967386-7fb45cc1-43a0-4600-831c-e3c1daa33ac5.png)

**Comment by snuffyDev** [comment]
Totally get what you mean. It’s leftover from way long ago that I haven’t touched really since, aside from tweaks and fixes. 

Along with a code rewrite, a UI touch up/reworking was in the cards as well. So perfect timing you posted this.

although not finished with the design, I’ve pushed the beginnings of some minor UI changes to production 
![0901F5CB-0061-4852-B654-78819581A64D](https://user-images.githubusercontent.com/72365477/161328298-52722411-bd45-4a5c-88af-fd65768d1c95.png)

I’ll leave this open for any other related inquiries you may have!

**Comment by IronMaltese** [comment]
Is getting rid of boxes around songs on artist's pages and the home page gonna be something for the UI overhaul? Also I think that using the space leftover from the boxes to make albums bigger would be a good idea since the albums on artists pages for the YouTube music app are big and I think it looks nice, also another UI improvement would be to get rid of the Grey lines between songs since I don't think it looks that good plus YouTube music doesn't have those lines (here's images of what I'm talking about)![image](https://user-images.githubusercontent.com/89056889/161340617-c615489b-8e95-40ed-9d3f-32f686a9a329.png)![image](https://user-images.githubusercontent.com/89056889/161340618-f4374897-98e6-4db5-8dcc-2419fef6305f.png)![image](https://user-images.githubusercontent.com/89056889/161340634-5ee8ea3f-b9f7-4e6d-8ac7-341cc013468c.png)![image](https://user-images.githubusercontent.com/89056889/161340653-ac996a11-6eb8-4783-ac13-3c766e9c948a.png)

**Comment by IronMaltese** [comment]
One last thing: the album cover should be bigger since Spotify's album size on mobile looks really nice since it's pretty big and I feel like Beatbump's current design has a lot of empty space ![image](https://user-images.githubusercontent.com/89056889/161341639-8868110c-27fb-411b-88eb-c267514c0026.png)

**Comment by snuffyDev** [comment]
The main reason for the lines between songs was in case it helps someone with a visual impairment since it helps “separate the concerns”. I think the borders should stay for that reason since I do intend on making Beatbump as accessible as it can be.

**Comment by IronMaltese** [comment]
Would you be open to add an option to enable/disable those lines in settings at some point

**Comment by IronMaltese** [comment]
I agree with you about that, and have deleted the comments I made about the album size, since I think it looks good now, but I wanna know how you want songs in albums to look, because some albums on Beatbump show the artists name under the song, and others don’t, so I’m just gonna ask which design is the right one Ex: 
![EDE0D5E9-BD5E-412C-A357-045EB8969DD0](https://user-images.githubusercontent.com/89056889/161661449-2eb6ea09-e3e6-4465-97b8-2cea611d154c.png)
![B426D87C-0AA4-4949-9127-C2AB87256AC1](https://user-images.githubusercontent.com/89056889/161661451-0a2cc014-d06a-4523-916d-471baf98f79d.png)

**Comment by IronMaltese** [comment]
Music.YouTube.com has this problem, but the app doesn't, so this feature is possible to implement in a stable way, but don't feel like you need to sacrifice stability or speed to implement this, also it'd be cool to add the song length after the artists name in albums like the YouTube music app does, since I think it looks good, but you don't need to do it if the artist name isn't parsed ![image](https://user-images.githubusercontent.com/89056889/162224739-fde42123-71b8-4dea-8a55-396879d213df.png)

**Comment by IronMaltese** [comment]
Also for the name of the artist in albums, could you get the name the same way you get the artists name for songs in custom playlists?

**Comment by IronMaltese** [comment]
Thanks for the fix :)
