### ISSUE TITLE
Request: Beatbump.ml is not accesible on privacy-oriented web browser

### ISSUE THREAD

**Issue by Kreyren** [snuffyDev/Beatbump#58]
I use random routing, fingerprint and emulated hardware GNU IceCat running in Xen para-virtualized environment which makes it impossible to access the website without sacrificing on privacy as cloudflare only lets through users which it can fingerprint for tracking..

### Proposal

Disable cloudflare gate

---

CC @snuffyDev

**Comment by snuffyDev** [comment]
By cloudflare gate, do you mean DNS? I'm looking for any settings in the Cloudflare dashboard but i'm not seeing any. If the issue stems from it being all hosted through Cloudflare, I'm trying to change that, but have been having trouble finding solutions for my current financial situation

**Comment by Kreyren** [comment]
The DNS is not a problem, but what it redirects to is.

This is the "cloudflare gate":

![2022-05-10_07-45](https://user-images.githubusercontent.com/11302521/167556814-68583659-abb8-41a0-b7d5-55d6264d1db9.png)

It's presented as "DDoS protection", but it makes the website not accessible unless cloudflare is able to fingerprint the user and track it across the web (and is also a MITM). -> I can't access the website without using static snapshots or using decloudflare to find the real server IP which breaks lot of websites (and takes around 10 min to finish and is basically a DoS).

It can be disabled in settings look for DDoS protection and disable it.

**Comment by snuffyDev** [comment]
Thanks for the clarification, I’m going to dive into the settings in a minute, so give me some time to do that. I’ll let you know what changes I make and will update when I do them. When that happens, let me know if things get fixed.

I’m on my phone right now, but I turned “security level” to low and disabled Integrity Checks. But I suspect more will be needed

**Comment by snuffyDev** [comment]
Knocked it down to 'Essentially Off' for security level. I have a few firewall and DNS rules in place that shouldn't block, but still filters out at least the bad stuff. Try it now, if it still blocks, give it 30 mins-1 hour to ensure the changes have taken effect. Update me with what happens!

**Comment by Kreyren** [comment]
So far seems to work perfectly! Thanks

**Comment by IronMaltese** [comment]
This issue can be closed
