### ISSUE TITLE
Background autoplay on latest iOS versions?

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#61]
Just wondering if there's a new workaround to get background autoplay working again on the latest iOS version, if not I can submit a PR for the wiki letting users know :)

**Comment by snuffyDev** [comment]
I haven’t found one yet, but I think I may be onto something. While it doesn’t *work* still, it’s more than what it did before!

As for the wiki, feel free to make a PR! Just leave up what’s there but make a note that states the work around doesn’t work for iOS versions after the one thats named. Thank you!

https://user-images.githubusercontent.com/72365477/170773038-dca15c14-6d08-4c8e-905f-7be3be6bbd9f.MOV

**Comment by IronMaltese** [comment]
I'll have the PR soon, but that video was really great to see, it'd be great this working without any setting changes🦀

**Comment by snuffyDev** [comment]
The progress I have at the moment is without any setting changes, so I’m hoping it’s do-able

**Comment by snuffyDev** [comment]
https://user-images.githubusercontent.com/72365477/171996163-1c4612cb-f810-4a4d-a4bd-a78348b30afa.mp4

Progress has been made! Now I think all I need to do is mess around with the process of loading the next track

**Comment by IronMaltese** [comment]
I'm glad you're making progress on this😆 With background audio working on the web app now, Beatbump will be entirely feature-rich on iOS, also I'm struggling more than I'd like to admit since I've never fetched upstream on GitHub before 😮‍💨

**Comment by Smig0l** [comment]
i am facing the same problem described on the [wiki](https://github.com/snuffyDev/Beatbump/wiki/Fixing-Background-Autoplay-on-iOS-15), i am on ios 15.5.
In the experimental features tab the items "GPU Process: *" are not present anymore. (see attached image)
when opened in safari the next track autoplay works well but when in the background it stops at the end.

**Comment by IronMaltese** [comment]
This is fixed, it's just really slow, I'm gonna close this and open a new issue
