### ISSUE TITLE
APGL license

### ISSUE THREAD

**Issue by BobIsMyManager** [snuffyDev/Beatbump#63]
From the readme of the project, it seems that you think you are using the AGPL-3.0, but when you look at the license file, it is using the GPL-3.0 license. Just for a quick reminder, the AGPL-3.0 is practically the same as the GPL-3.0 besides the fact that it requires that source code must be shared in more senarios, such as using it as a backend.

To be able to change the license, you must have explicit permission from all copyright holders (in this senario, this would be the contributers). Commenting below that you give permission to change the license to AGPL-3.0 should be enough.
- [x] @snuffyDev 
- [x] @IronMaltese 

I would also like to mention that although AGPL-3.0 only seems to have benefits for backend software, using it instead of GPL-3.0 allows for much simpler compatibility with other AGPL-3.0 software (such as libraries) and if there is any software that *could* possibly be used in a backend, it would be protected.

On top of that, I would recommend you change the license of all branches of this projet.

**Comment by IronMaltese** [comment]
I give permission to change the license🦭

**Comment by BobIsMyManager** [comment]
> This project should have a terms of agreement to make sure the license can be changed in the future

Just so you know, that's called a CLA (Contributer License Agreement) hat could work, but you should know it also has its downsides:

- It would require every time someone crontributes for them to explicitly disclose that they are handing rights to the code to snuffyDev, which is not only inconvinient for some, but may make few not want to contribute
- It would also mean that if one day snuffyDev decided to make it proprietary, he could

It's also worth mentioning that afaik, there shouldn't really ever need to be a change of license after this unless snuffyDev has a change of heart, as if a change was needed to fix a loophole in the license, the AGPL-3.0 allows for upgrading the license to a later version of this license if you want without anyone elses permission
>  If the Program specifies that a certain numbered version of the GNU Affero General Public License "or any later version" applies to it, you have the option of following the terms and conditions either of that numbered version or of any later version published by the Free Software Foundation. If the Program does not specify a version number of the GNU Affero General Public License, you may choose any version ever published by the Free Software Foundation.

**Comment by IronMaltese** [comment]
Thanks for the response, I didn't realize the GPL could be upgraded without permission of contributors

**Comment by BobIsMyManager** [comment]
yep, from what I can see this is the case by deafult when I look at the license:
> This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

As the brackets should mean that they can be ignored, but if you want to can remove them, just to be safe.

**Comment by snuffyDev** [comment]
Apologies for the late response! I just saw this. But great catch! I'm fairly fresh in terms of licensing, From what I can remember when I set the license, I used what https://choosealicense.com/licenses/ gave me but I could be mistaken.

Appreciate this so much!
