### ISSUE TITLE
Unable to play some tracks

### ISSUE THREAD

**Issue by onny** [snuffyDev/Beatbump#7]
Hey,
somehow I was able to play specific tracks, for example:
https://beatbump.ml/listen?id=TtpczrnqklU

Best regards
Jonas

**Comment by snuffyDev** [comment]
Hello, my bad for the late response I didn’t see this til now. Some sleuthing in DevTools showed me that YouTube was serving a DASH .mpd stream for that track, which as far as I understand they do for *some* tracks.

This should be fixed now, I tested it with that track in your original issue and it appears to play fine now! Thanks for the heads up!!
