### ISSUE TITLE
Remember search preference

### ISSUE THREAD

**Issue by shuvashish76** [snuffyDev/Beatbump#72]
Currently we've these options
- Songs
- Videos
- Artists
- All Playlists
- Community Playlists

Pick "All Playlists" then search but when you try to search something next time it pick "Songs" option by default. Would be nice if the site could remember users' last used search preference.

**Comment by snuffyDev** [comment]
Noted! Was re-implementing the settings so I'll add this to them!

**Comment by IronMaltese** [comment]
I think a better solution to this problem would be for the implementation of Spotify's method for filtering searches and it can reset to songs for everytime except when the user is on the results page with an already selected filter ![image](https://user-images.githubusercontent.com/89056889/176121574-f1b0ca98-64ea-4949-9ca8-afed7ed076a2.jpeg)

**Comment by snuffyDev** [comment]
Although this URL is a preview, here's what I managed so far (check the settings!)

https://beatbump-preview.beatbump.workers.dev/home

**Comment by IronMaltese** [comment]
This can probably be closed since #99 implemented my previous suggestion in a better way and this feature seems to be fully implemented
