### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by locxter** [snuffyDev/Beatbump#81]
First of all thanks for this awesome project!
I was searching for an Invidious like Youtube Music frontend for a long time a have finally found it here!

Sadly the search function never works for me, regardless of which browser I am using (tried with hardened and normal Firefox, Chromium and even a default Safari).
This behaviour also is the same on the main and rewrite preview site, however there seem to be less errors on the rewritten version.
Here a some screenshots detailing the problem with the song "Shivers" as an example:
![firefox](https://user-images.githubusercontent.com/54595101/180455239-b7eba67c-48dc-4f62-b851-efd33f298c70.png)
![firefox-rewrite](https://user-images.githubusercontent.com/54595101/180455260-e009ad3c-9130-4895-a0a4-850a52754758.png)
![chromium](https://user-images.githubusercontent.com/54595101/180455274-7b8ff246-09d4-4e5b-8cdb-d0f535ad2bc6.png)
![chromium-rewrite](https://user-images.githubusercontent.com/54595101/180455284-3f2a3650-67fe-4b77-9669-d0d32316a773.png)

Hope we can fix this!
I am not primarly a web developer, but would be proud to help if needed...

**Comment by snuffyDev** [comment]
Are you using 'Private/Incognito' mode?

**Comment by locxter** [comment]
No, but my primary Firefox is extremely tweaked. Nevertheless the behaviour is always the same with all the browsers and devices I tried. This includes default configs of Firefox, Chrome (also the Chromium image I added is stock) and Safari.
Therefore I would say that it isn't browser specific.
I am from Germany, which might be useful information, if it is related to some sort of geoblocking.

**Comment by locxter** [comment]
It really seems to be a geolocation related problem.
I tried using the site on my phone with Riseup VPN and when switching to an US based location everything works fine, even though it does not work with any EU based lcoation.
I also looked a bit into the API (the one described on the deployment wiki) and here in Germany without any VPN I just get `{"error":"No Results Found"}` as the response.
Weirdly enough the search suggestions always work and return the expected data (`[{"query":"shivers ed sheeran","id":0},{"query":"shivers","id":1},{"query":"shivers ed sheeran remix","id":2},{"query":"shivers ofenbach remix","id":3},{"query":"shivers remix","id":4},{"query":"shivers acoustic","id":5},{"query":"shivers ed sheeran lyrics","id":6}]`).

**Comment by Smig0l** [comment]
What about setting a pre-populated visitordata() parameter in src/routes/home/index.json.ts?
Or forcing a known x-goog-visitor-id?

**Comment by locxter** [comment]
Good to hear that I am not the only one with this problem.
I just spun up a dev instance to further debug the problem and as it turns out the Youtube Music API does answer with something useful.
It seems like the data is just formatted differently and therefore Beatbump can not process it.
Here is a dump of the response:
[response.zip](https://github.com/snuffyDev/Beatbump/files/9175999/response.zip)
Maybe a different parser for the EU format could be implemented to solve this problem?
I also tried adding visitorData and x-goog-visitor-id to the request, but it doesn't change anything.

**Comment by snuffyDev** [comment]
It should be live on the preview site as of right now! I implemented your changes, so let me know if it fixes it. If fixed, I'll merge your PR (and migrate your changes over to the new code + a comment referencing the PR just to ensure it'll be attributed to you in some form!)

Preparing the rewrite still to publish to GitHub, but by the looks of it I would say the update should be ready to publish today or tomorrow!

**Comment by locxter** [comment]
Just took a look and it works flawlessly now.
Also awesome to hear that the rewrite comes together...

**Comment by locxter** [comment]
> Interesting. Would you mind (in an incognito window, for the sake of privacy) going to YouTube Music and doing these steps:
> 
>     * Once YTM home page is loaded, open up Devtools
> 
>     * Go to “network” tab (keep Devtools open)
> 
>     * Search for a song
> 
>     * Click the “chip” or small button near the top (IIRC, doing this from memory) that says “Songs”
> 
>     * Select the last request that doesn’t have `?ctoken`
> 
> 
> Then once you have the JSON response, could you send me it either through a GitHub Gist or with Pastebin? No worries if you're unable to for any reason, only reason I ask is out of my own curiosity!
> 
> Here's a video demonstrating what I mean: https://user-images.githubusercontent.com/72365477/180807253-285b61f3-acc1-44bf-b444-0bbcff29dbc0.mp4
> 
> I am running a build right now which should be live at the preview site (https://beatbump-preview.beatbump.workers.dev/) within a few minutes! I will reply once it's live

The response is exactly the same as `raw-berlin.json` in `test.zip` in my previous comment

**Comment by snuffyDev** [comment]
Noted! Will merge your PR! Glad to hear it works!

**Comment by Smig0l** [comment]
sorry to reopen this but it worked for few hours...
now it says "all result for .." but the response is empty
