### ISSUE TITLE
[BUG]Autoplay next track on Safari IOS

### ISSUE THREAD

**Issue by Smig0l** [snuffyDev/Beatbump#84]
I am opening a new issue for visibility:

i am facing the same problem described on the [wiki](https://github.com/snuffyDev/Beatbump/wiki/Fixing-Background-Autoplay-on-iOS-15), i am on ios 15.5.
In the experimental features tab the items "GPU Process: *" are not present anymore. (see attached image)
when opened in safari, the next-track-autoplay works well ,but if i put safari in background or lock the screen it "stops"(not playing in cc) when it reaches the end of the track.
![image](https://user-images.githubusercontent.com/109904155/180742263-f40dc956-f5fd-468b-bfcc-f1da3de86341.png)

__Originally posted by @Smig0l in https://github.com/snuffyDev/Beatbump/issues/61#issuecomment-1193792156__

IOS 15.5 
Tried both Chrome and Safari, master and rewrite branch.
idk if is relevant but i am in the EU.

I appreciate your work‼️
Tell me if u need me to debug and screenshot requests.
Thanks

**Comment by snuffyDev** [comment]
Unfortunately, at the present moment it seems as if I'm unable to fix this. I've managed to *almost* get it to work again, but it appears that according to https://bugs.webkit.org/show_bug.cgi?id=173332 it's a known problem that's been patched, and is waiting to be released in a future Safari/WebKit update

**Comment by Smig0l** [comment]
nvm it was fixed in IOS [15.6](https://webkit.org/blog/13009/new-webkit-features-in-safari-15-6/)!!

>  Media:
> - Fixed blank video playback with only audio
> - Fixed replaceTrack with different constraints preventing sending packets
> - Fixed WebAudio playback rate speeding up for a few seconds when using createMediaElementSource
> - Fixed stalled playback when seeking in a xHE-AAC track backed by a SourceBuffer
> - **Fixed starting audio playback in Safari when the device is locked**
> - Fixed playback for video when the timeline sometimes goes backward at the start of playback
> - Fixed capturing and rendering audio simultaneously

Tried now and it seems working

**Comment by IronMaltese** [comment]
It doesn't seem to work for me, I'm using https://beatbump-preview.beatbump.workers.dev/search/Mf%2520doom?filter=song is there another preview site I should be using for this to work consistently

**Comment by Smig0l** [comment]
Seems the issue returned after IOS 16.0.2 update.
Anyone can confirm?

**Comment by IronMaltese** [comment]
> Seems the issue returned after IOS 16.0.2 update.
> Anyone can confirm?

I haven't updated yet, are you using the web app or safari

Also try using a separate browser to see if it's an issue with safari or iOS
