### ISSUE TITLE
Music player redesign

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#87]
The mobile music player on the bottom of the screen should turn from this: 
![image](https://user-images.githubusercontent.com/89056889/181661923-a6118105-10ac-40ad-b458-c94b81acf092.jpeg)

Into looking like this: (image from YouTube music iOS app)
![image](https://user-images.githubusercontent.com/89056889/181662058-2fec9261-4f53-4669-819d-79e1cbe8fb9c.jpeg)

The three dots on Beatbump should move here: 
![image](https://user-images.githubusercontent.com/89056889/181662220-a96c1417-7d3a-4819-bd2c-03227a9da182.jpeg)

**Comment by IronMaltese** [comment]
The user should also be able to long press on the bottom bar to show the carousel

**Comment by snuffyDev** [comment]
In progress now 🎉

https://user-images.githubusercontent.com/72365477/218265987-b961939c-a5b5-4ed1-97d3-c3ba5c4ba367.MOV

**Comment by snuffyDev** [comment]
@IronMaltese There's a lot on it's way!

https://user-images.githubusercontent.com/72365477/218915558-7da7026f-efc9-47ce-a729-094543f38fe3.mp4

**Comment by snuffyDev** [comment]
https://user-images.githubusercontent.com/72365477/218957157-aa9af8e2-aec9-437b-bbdb-8f595b6139e4.MOV

**Comment by IronMaltese** [comment]
Woah! It's great to see how much has been worked on, seeing even the smallest change added never fails to raise my spirits

**Comment by IronMaltese** [comment]
Also! I don't want to crowd the issues with this, but making the Up Next and Related buttons clickable instead of having to swipe up everytime would be great :D

**Comment by snuffyDev** [comment]
https://user-images.githubusercontent.com/72365477/219923121-0c7de77f-bb34-4120-af9a-8d336e984590.mp4

**Comment by snuffyDev** [comment]
https://user-images.githubusercontent.com/72365477/221352613-bb990eff-f708-44f9-a360-fbaed57d4a28.MOV

Gonna commit today, should be in a full release soon for all instances!
