### ISSUE TITLE
iOS Web App isn't working

### ISSUE THREAD

**Issue by IronMaltese** [snuffyDev/Beatbump#92]
https://user-images.githubusercontent.com/89056889/184686810-29a99b71-47dc-44fe-afa2-8c1891a6af47.MOV

**Comment by snuffyDev** [comment]
It works for me, try visiting in Safari. I guess that’ll “force update” it?

**Comment by IronMaltese** [comment]
> It works for me, try visiting in Safari. I guess that’ll “force update” it?

This has been happening for a week already, and nothing I've done has fixed it

Other PWAs such as Nitter and Libreddit work

**Comment by IronMaltese** [comment]
Working now :)
