### ISSUE TITLE
Export and import a favorites and playlists as a file

### ISSUE THREAD

**Issue by noughtmare** [snuffyDev/Beatbump#97]
I'm using Firefox containers extensively. In practice that means that all my website data gets erased after I close my browser tabs (unless I explicitly make a persisted container). That means that my playlists and favorites could easily be lost. The webrtc synchronization feature doesn't help in this case.

So, I would like to request a feature that allows me to export and import my favorites and playlists as a file, preferably in a format that is easy to manipulate with third party tools like JSON.

**Comment by snuffyDev** [comment]
Don't worry, already on it https://github.com/snuffyDev/Beatbump/blob/master/app/src/lib/db.ts#L352 ;)

All that I'm working on now is figuring out the best way to add it to the UI, along with cleaning up the library/custom playlist code.

Hopefully it should be implemented, at least in a very barebones form, within the next few hours ideally. Worst case scenario it might take a day or two, but lets hope that won't happen!

**Comment by snuffyDev** [comment]
Closing this issue as well since it has now been added, as mentioned in #96
